export const tasks = [
	{
		id: 1,
		title: "Install jsonwebtoken",
		description: "Install jsonwebtoken",
		completed: false,
		priority: "high",
		createdAt: new Date("2026-02-01T10:20:00Z"),
	},
	{
		id: 2,
		title: "Set up environment",
		description: "Install Node.js, npm, and git",
		completed: true,
		priority: "low",
		createdAt: new Date("2026-02-01T08:00:00Z"),
	},
	{
		id: 3,
		title: "Create a new project",
		description:
			"Create a new project using the Express application generator",
		completed: true,
		priority: "low",
		createdAt: new Date("2026-02-01T08:10:00Z"),
	},
	{
		id: 4,
		title: "Install nodemon",
		description: "Install nodemon as a development dependency",
		completed: true,
		priority: "low",
		createdAt: new Date("2026-02-01T08:20:00Z"),
	},
	{
		id: 5,
		title: "Install Express",
		description: "Install Express",
		completed: false,
		priority: "high",
		createdAt: new Date("2026-02-01T08:30:00Z"),
	},
	{
		id: 6,
		title: "Install Mongoose",
		description: "Install Mongoose",
		completed: false,
		priority: "low",
		createdAt: new Date("2026-02-01T08:40:00Z"),
	},
	{
		id: 7,
		title: "Install Morgan",
		description: "Install Morgan",
		completed: false,
		priority: "medium",
		createdAt: new Date("2026-02-01T08:50:00Z"),
	},
	{
		id: 8,
		title: "Install body-parser",
		description: "Install body-parser",
		completed: false,
		priority: "low",
		createdAt: new Date("2026-02-01T09:00:00Z"),
	},
	{
		id: 9,
		title: "Install cors",
		description: "Install cors",
		completed: false,
		priority: "low",
		createdAt: new Date("2026-02-01T09:10:00Z"),
	},
	{
		id: 10,
		title: "Install passport",
		description: "Install passport",
		completed: false,
		priority: "high",
		createdAt: new Date("2026-02-01T09:20:00Z"),
	},
	{
		id: 11,
		title: "Install passport-local",
		description: "Install passport-local",
		completed: false,
		priority: "medium",
		createdAt: new Date("2026-02-01T09:30:00Z"),
	},
	{
		id: 12,
		title: "Install passport-local-mongoose",
		description: "Install passport-local-mongoose",
		completed: false,
		priority: "high",
		createdAt: new Date("2026-02-01T09:40:00Z"),
	},
	{
		id: 13,
		title: "Install express-session",
		description: "Install express-session",
		completed: true,
		priority: "low",
		createdAt: new Date("2026-02-01T09:50:00Z"),
	},
	{
		id: 14,
		title: "Install connect-mongo",
		description: "Install connect-mongo",
		completed: false,
		priority: "low",
		createdAt: new Date("2026-02-01T10:00:00Z"),
	},
	{
		id: 15,
		title: "Install dotenv",
		description: "Install dotenv",
		completed: true,
		priority: "medium",
		createdAt: new Date("2026-02-01T10:10:00Z"),
	},
	{
		id: 16,
		title: "Install jsonwebtoken",
		description: "Install jsonwebtoken",
		completed: false,
		priority: "high",
		createdAt: new Date("2026-02-01T10:20:00Z"),
	},
];
